[toolchain]
package_manager = "yarn"
anchor_version = "0.28.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
diamond_token = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "mocha"

[test]
startup_wait = 10000

[test.validator]
url = "http://127.0.0.1:8899"

[workspace]
members = [
    "programs/diamond_token"
]
