[package]
name = "diamond_token"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "diamond_token"

[dependencies]
anchor-lang = { version = "=0.31.1", features = ["idl"] }
anchor-spl = "=0.31.1"
thiserror = "1.0"
pyth-sdk-solana = "0.7"
spl-memo = "3.0.1" 
